a = input('Digite algo: ')
print('/o tipo primitivo desse valor é: ', type(a))
print('Só tem espaço? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('E alfanumerico? ', a.isalnum())
print('Está em maiusculas? ', a.isupper())
print('Está em minúsculas? ', a.islower())
print('Está capitalizado? ', a.istitle())
